//
// debugger_char.inc
//
// BSD 3-Clause License
// 
// Copyright (c) 2024, Shinobu Hashimoto
// 
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
// 
// 1. Redistributions of source code must retain the above copyright notice, this
//    list of conditions and the following disclaimer.
// 
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
// 
// 3. Neither the name of the copyright holder nor the names of its
//    contributors may be used to endorse or promote products derived from
//    this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//

`ifndef _INCLUDED_DEBUGGER_CHAR_INC_
`define _INCLUDED_DEBUGGER_CHAR_INC_

/***********************************************************************
 * キャラクターコード定義
 ***********************************************************************/
localparam  CHAR_LF     = 8'h0A;
localparam  CHAR_CR     = 8'h0D;
localparam  CHAR_SPC    = 8'h20;
localparam  CHAR_COMMA  = 8'h2C;
localparam  CHAR_DOT    = 8'h2E;
localparam  CHAR_0      = 8'h30;
localparam  CHAR_1      = 8'h31;
localparam  CHAR_2      = 8'h32;
localparam  CHAR_3      = 8'h33;
localparam  CHAR_4      = 8'h34;
localparam  CHAR_5      = 8'h35;
localparam  CHAR_6      = 8'h36;
localparam  CHAR_7      = 8'h37;
localparam  CHAR_8      = 8'h38;
localparam  CHAR_9      = 8'h39;
localparam  CHAR_A      = 8'h41;
localparam  CHAR_B      = 8'h42;
localparam  CHAR_C      = 8'h43;
localparam  CHAR_D      = 8'h44;
localparam  CHAR_E      = 8'h45;
localparam  CHAR_F      = 8'h46;
localparam  CHAR_G      = 8'h47;
localparam  CHAR_H      = 8'h48;
localparam  CHAR_I      = 8'h49;
localparam  CHAR_J      = 8'h4A;
localparam  CHAR_K      = 8'h4B;
localparam  CHAR_L      = 8'h4C;
localparam  CHAR_M      = 8'h4D;
localparam  CHAR_N      = 8'h4E;
localparam  CHAR_O      = 8'h4F;
localparam  CHAR_P      = 8'h50;
localparam  CHAR_Q      = 8'h51;
localparam  CHAR_R      = 8'h52;
localparam  CHAR_S      = 8'h53;

localparam  CHAR_V      = 8'h56;
localparam  CHAR_W      = 8'h57;

localparam  CHAR_a      = 8'h61;
localparam  CHAR_b      = 8'h62;
localparam  CHAR_c      = 8'h63;
localparam  CHAR_d      = 8'h64;
localparam  CHAR_e      = 8'h65;
localparam  CHAR_f      = 8'h66;

localparam  CHAR_n      = 8'h6E;
localparam  CHAR_o      = 8'h6F;
localparam  CHAR_p      = 8'h70;
localparam  CHAR_q      = 8'h71;
localparam  CHAR_r      = 8'h72;
localparam  CHAR_s      = 8'h73;
localparam  CHAR_t      = 8'h74;

`endif
